# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  integration:
    runs-on: ubuntu-latest

    services:
      rippled:
        image: xrptipbot/rippled:latest
        ports:
          6006:6006
        with:
          args: --standalone

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc # From https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: yarn install
    - run: yarn test:integration