# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  build_with_nvm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc # From https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn build

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn build

  integration:
    runs-on: ubuntu-latest

    container: 
      image: node:10.16-jessie

    services:
      rippled:
        image: natenichols/rippled-standalone:latest
        ports:
        - 6006:6006

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc # From https://github.com/actions/setup-node/issues/32#issuecomment-525791142
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: yarn install
    - run: yarn test:integration
      env:
        HOST: rippled
        PORT: ${{ job.services.rippled.ports[6006] }}
